### ISSUE TITLE
example broken

### ISSUE THREAD

**Issue by michielbdejong** [rdf-ext-archive/rdf-examples#11]
I saved https://github.com/rdf-ext/rdf-examples/blob/develop/parse-jsonld-serializer-ntriples.js to a file, installed the three modules used, and try to run it, but the result was as follows:

```sh
~/gh/inrupt/test $ node json-ld-to-turtle.js
(node:6892) UnhandledPromiseRejectionWarning: TypeError: quad.toCanonical is not a function
    at ParserStream.SerializerStream.input.on (/Users/michiel/gh/inrupt/test/node_modules/rdf-serializer-ntriples/lib/SerializerStream.js:10:22)
    at ParserStream.emit (events.js:189:13)
    at addChunk (/Users/michiel/gh/inrupt/test/node_modules/rdf-parser-jsonld/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/Users/michiel/gh/inrupt/test/node_modules/rdf-parser-jsonld/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at ParserStream.Readable.push (/Users/michiel/gh/inrupt/test/node_modules/rdf-parser-jsonld/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at rawGraph.(anonymous function).forEach (/Users/michiel/gh/inrupt/test/node_modules/rdf-parser-jsonld/lib/ParserStream.js:79:16)
    at Array.forEach (<anonymous>)
    at Object.keys.forEach (/Users/michiel/gh/inrupt/test/node_modules/rdf-parser-jsonld/lib/ParserStream.js:78:28)
    at Array.forEach (<anonymous>)
    at ParserStream.toJson.then.then (/Users/michiel/gh/inrupt/test/node_modules/rdf-parser-jsonld/lib/ParserStream.js:75:29)
(node:6892) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6892) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by michielbdejong** [comment]
Bump
